### ISSUE TITLE
how solve this error?

### ISSUE THREAD

**Issue by johnfelipe** [KhushrajRathod/Kuizzy#23]
warning ../package.json: No license field
	$ node app.js
	listening on *:3000
	A user connected
	A user connected
	A user connected
	A user connected
	/root/Kuizzy/app.js:252
					userPointsMap[socket.id][1]++;
								 ^

	TypeError: Cannot read property '1' of undefined
		at EventEmitter.<anonymous> (/root/Kuizzy/app.js:252:30)
		at EventEmitter.emit (events.js:203:15)
		at Timeout._onTimeout (/root/Kuizzy/app.js:199:61)
		at ontimeout (timers.js:436:11)
		at tryOnTimeout (timers.js:300:5)
		at listOnTimeout (timers.js:263:5)
		at Timer.processTimers (timers.js:223:10)
	error Command failed with exit code 1.
	info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by khrj** [comment]
Hi, could you list down the steps to reproduce this issue? How exactly did this error occur?

**Comment by johnfelipe** [comment]
I'm install correctly
And use host and 4 players and in question 4 show that errror and stop game, pls tell me how solve it...
